spring.application.name: springboot-graphql-application
servlet.multipart.max-file-size: 2MB
server.http2.enabled: true

graphql.servlet.maxQueryDepth: 100
graphql.servlet.exception-handlers-enabled: false
graphql.servlet.tracingEnabled: false

graphql.playground.enabled: true
